name: flash_chat
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.0
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  cloud_firestore: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.1.7+1

flutter_native_splash:
  color: "#ffffff"
  image: "images/logo.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
